//carreras
export const GET_CARRERAS = 'GET_CARRERAS';
export const GET_ALL_CARRERAS = 'GET_ALL_CARRERAS';
export const GET_SOLICITUDES = 'GET_SOLICITUDES';
export const GET_ASIGNACIONES = 'GET_ASIGNACIONES';
export const GET_PANEL1 = 'GET_PANEL1';
export const GET_ACTA1 = 'GET_ACTA1';
export const GET_DETALLE_ACTA1 = 'GET_DETALLE_ACTA1';
export const GET_DETALLE_SOL = 'GET_DETALLE_SOL';
export const GET_ESTUDIANTES = 'GET_ESTUDIANTES';
export const GET_DATEACTA = 'GET_DATEACTA';
export const GET_MESACTA = 'GET_MESACTA';
export const GET_ANIOACTA = 'GET_ANIOACTA';
export const GET_TACTA = 'GET_TACTA';
export const GET_SDIA = 'GET_SDIA';
export const GET_HORADEFENSA = 'GET_HORADEFENSA';
export const GET_ACTUALFECHA = 'GET_ACTUALFECHA';
export const GET_ACTUALFECHASOL = 'GET_ACTUALFECHASOL';
export const GET_HISTORIALESTUDIANTE = 'GET_HISTORIALESTUDIANTE';

export const GET_ACTUAL_CORRELATIVO = 'GET_ACTUAL_CORRELATIVO';

//docentes
export const GET_DOCENTE = 'GET_DOCENTE';

export const GET_DOCENTE_P1 = 'GET_DOCENTE_P1';
// reportes docentes
export const GET_REPORTE_DOCENTEP1 = 'GET_REPORTE_DOCENTEP1';
export const GET_REPORTE_DOCENTEP2 = 'GET_REPORTE_DOCENTEP2';
export const GET_REPORTE_DOCENTEP3 = 'GET_REPORTE_DOCENTEP3';
export const GET_REPORTE_DOCENTEPA = 'GET_REPORTE_DOCENTEPA';
export const GET_REPORTE_DOCENTEAS = 'GET_REPORTE_DOCENTEAS';

// autentificacion
export const GET_AUTHENTICATE = 'GET_AUTHENTICATE';
//reporte de admin event
export const GET_REPORTE_EVENTO = 'GET_REPORTE_EVENTO';