export const SET_CARRERAS = 'SET_CARRERAS';
export const SET_ALL_CARRERAS = 'SET_ALL_CARRERAS';
export const SET_SOLICITUDES = 'SET_SOLICITUDES';
export const SET_ASIGNACIONES = 'SET_ASIGNACIONES';
export const SET_PANEL1 = 'SET_PANEL1';
export const SET_ACTA1 = 'SET_ACTA1';
export const SET_DETALLE_ACTA1 = 'SET_DETALLE_ACTA1';
export const SET_DETALLE_SOL = 'SET_DETALLE_SOL';
export const SET_ESTUDIANTES = 'SET_ESTUDIANTES';
export const SET_DATEACTA = 'SET_DATEACTA';
export const SET_MESACTA = 'SET_MESACTA';
export const SET_ANIOACTA = 'SET_ANIOACTA';
export const SET_TACTA = 'SET_TACTA';
export const SET_SDIA = 'SET_SDIA';
export const SET_HORADEFENSA = 'SET_HORADEFENSA';
export const SET_ACTUALFECHA = 'SET_ACTUALFECHA';
export const SET_ACTUALFECHASOL = 'SET_ACTUALFECHASOL';
export const SET_HISTORIALESTUDIANTE = 'SET_HISTORIALESTUDIANTE';
export const SET_ACTUAL_CORRELATIVO = 'SET_ACTUAL_CORRELATIVO';
//docentes
export const SET_DOCENTE = 'SET_DOCENTE';
export const SET_DOCENTE_P1 = 'SET_DOCENTE_P1';
//reportes docentes
export const SET_REPORTE_DOCENTEP1 = 'SET_REPORTE_DOCENTEP1';
export const SET_REPORTE_DOCENTEP2 = 'SET_REPORTE_DOCENTEP2';
export const SET_REPORTE_DOCENTEP3 = 'SET_REPORTE_DOCENTEP3';
export const SET_REPORTE_DOCENTEPA = 'SET_REPORTE_DOCENTEPA';
export const SET_REPORTE_DOCENTEAS = 'SET_REPORTE_DOCENTEAS';

// autentificacion
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';
//Reporte main event
export const SET_REPORTE_EVENTO = 'SET_REPORTE_EVENTO';
